name: $name
version: $version
main: net.mvndicraft.mvndimisc.MvndiMisc
api-version: '1.21'
authors: [ tlm920 ]
description: Core plugin for minigame management on Mvndicraft
website: mvndicraft.net
folia-supported: true
dependencies:
  server:
    packetevents:
      load: BEFORE
      required: true
    MvndiEquipment:
      load: BEFORE
      required: true
    MvndiPlayers:
      load: BEFORE
      required: true
    MvndiStats:
      load: BEFORE
      required: true
    MvndiMMO:
      load: BEFORE
      required: false
